### ISSUE TITLE
Sharing model and dataset on the Hugging Face Hub

### ISSUE THREAD

**Issue by davanstrien** [shenghanlin/SeismicFoundationModel#2]
Very cool work! Would be great to also make the model weights and datasets available via the Hugging Face Hub so more people can find this work. Happy to help with that if it's of interest 🤗

**Comment by shenghanlin** [comment]
Thank you for your valuable suggestion! We highly value community feedback and opportunities for collaboration, recognizing the importance of sharing our model weights and datasets on the Hugging Face Hub. This will not only increase the visibility of our work but also foster interactions and collaborations with the global research and development community.

We plan to publish our models and datasets on Hugging Face after further optimizations and enhancements have been made. This approach ensures that community members have access to the most up-to-date and accurate resources, while also allowing us to benefit from the community's feedback for further improvements.

Thank you again for your willingness to help, which is greatly appreciated. As we prepare for publication on Hugging Face, we may seek further advice and support from you. We look forward to more exchanges and collaborations with you and the broader community in the future.
