### ISSUE TITLE
Links to data and pretrained model seem to be broken

### ISSUE THREAD

**Issue by NotAThrowAwayAccount** [shenghanlin/SeismicFoundationModel#4]
Checked both links to data and pretrained model today. All of them show this:

<img width="413" alt="image" src="https://github.com/shenghanlin/SeismicFoundationModel/assets/164153788/2b27060c-ccd7-4bf9-a2fd-5e02449a0eae">

**Comment by Advika1030** [comment]
I faced this issue today too

**Comment by shenghanlin** [comment]
Thank you for reaching out and expressing your interest in the Seismic Foundation Model (SFM) project. I checked our shared resources on the cloud storage and, to my surprise, found that our storage space had reached its capacity. This unexpected issue led to the automatic cancellation of the share links by our cloud storage system, which in turn, resulted in the accessibility issues you've encountered. I sincerely apologize for the inconvenience this has caused you and appreciate your understanding as we work through this unforeseen complication.

Rest assured, I am currently in the process of identifying an alternative and effective method to share the SFM project's data and models. My primary aim is to ensure easy and uninterrupted access to these resources for researchers like yourself, who are keen on advancing the field of seismic data analysis.

I will keep you updated on our progress and intend to release the new sharing links as soon as possible. Your patience during this time is greatly appreciated. In the meantime, should you have any further questions or require additional information, please do not hesitate to contact me.

**Comment by shenghanlin** [comment]
The link has now been repaired
